#controllers:
#    resource: ../../src/Controller/
#    type: annotation
    
web_controller:
    resource: ../../src/Controller/Web/
    type: annotation
rest_controller:
    resource: ../../src/Controller/Api/
    type: annotation
    #prefix: /api
