<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGsmmkrm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGsmmkrm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGsmmkrm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGsmmkrm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGsmmkrm\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Gsmmkrm',
    'container.build_id' => '40968ceb',
    'container.build_time' => 1539667393,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGsmmkrm');
